import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "SQL Master",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="bg-gradient-to-b from-gray-900 to-gray-800 text-white">
          {/*header*/}
          <Header />
          <main> {children}</main>
          {/* footer*/}
          <Footer />
        </div>
      </body>
    </html>
  );
}
